### ISSUE TITLE
The integration seems to be failing since upgrading HA to 2024.3

### ISSUE THREAD

**Issue by thematrixdev** [tsunglung/foodpanda#2]
Hello there,

The integration used to be working.

It seems to be failing since upgrading.

![image](https://github.com/tsunglung/foodpanda/assets/19472561/7dcef5b8-65be-4a1b-bdb0-370bb1d85ad6)

I have re-logined Foodpanda and obtained a new set of tokens, still failed.

Thanks.

**Comment by thematrixdev** [comment]
It works today without any modification to configurations.
Maybe it was just a temporary issue.
Thanks.

**Comment by niceboygithub** [comment]
Foodpanda start to check frequently access and block the access. The blocking will be removed after few hours or days.

**Comment by tsunglung** [comment]
Foodpanda start to check frequently access and block the access. The blocking will be removed after few hours or days.

Recommends to use account to login.
